# .github/workflows/terraform.yml

name: Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET: terraform-state-bucket

jobs:

  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan (Dev)
      run: |
        terraform workspace select dev || terraform workspace new dev
        terraform plan -out=plan.tfplan

    - name: Terraform Apply (Dev)
      run: terraform apply plan.tfplan

    - name: Terraform Plan (Staging)
      run: |
        terraform workspace select staging || terraform workspace new staging
        terraform plan -out=plan.tfplan

    - name: Terraform Apply (Staging)
      run: terraform apply plan.tfplan

    - name: Terraform Plan (Production)
      run: |
        terraform workspace select prod || terraform workspace new prod
        terraform plan -out=plan.tfplan

    - name: Terraform Apply (Production)
      run: terraform apply plan.tfplan